;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                      Room palette data include file                      ;;
;;                        code/palettes/roompals.asm                        ;;
;;                                                                          ;;
;;              Generated using the Landstalker Editor v0.3.4:              ;;
;;              https://github.com/lordmir/landstalker_editor               ;;
;;                For use with the Landstalker disassembly:                 ;;
;;              https://github.com/lordmir/landstalker_disasm               ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


RoomPal01:           incbin   "assets_packed/graphics/roompalettes/pal001.pal"
RoomPal02:           incbin   "assets_packed/graphics/roompalettes/pal002.pal"
RoomPal03:           incbin   "assets_packed/graphics/roompalettes/pal003.pal"
RoomPal04:           incbin   "assets_packed/graphics/roompalettes/pal004.pal"
RoomPal05:           incbin   "assets_packed/graphics/roompalettes/pal005.pal"
RoomPal06:           incbin   "assets_packed/graphics/roompalettes/pal006.pal"
RoomPal07:           incbin   "assets_packed/graphics/roompalettes/pal007.pal"
RoomPal08:           incbin   "assets_packed/graphics/roompalettes/pal008.pal"
RoomPal09:           incbin   "assets_packed/graphics/roompalettes/pal009.pal"
RoomPal10:           incbin   "assets_packed/graphics/roompalettes/pal010.pal"
RoomPal11:           incbin   "assets_packed/graphics/roompalettes/pal011.pal"
RoomPal12:           incbin   "assets_packed/graphics/roompalettes/pal012.pal"
RoomPal13:           incbin   "assets_packed/graphics/roompalettes/pal013.pal"
RoomPal14:           incbin   "assets_packed/graphics/roompalettes/pal014.pal"
RoomPal15:           incbin   "assets_packed/graphics/roompalettes/pal015.pal"
RoomPal16:           incbin   "assets_packed/graphics/roompalettes/pal016.pal"
RoomPal17:           incbin   "assets_packed/graphics/roompalettes/pal017.pal"
RoomPal18:           incbin   "assets_packed/graphics/roompalettes/pal018.pal"
RoomPal19:           incbin   "assets_packed/graphics/roompalettes/pal019.pal"
RoomPal20:           incbin   "assets_packed/graphics/roompalettes/pal020.pal"
RoomPal21:           incbin   "assets_packed/graphics/roompalettes/pal021.pal"
RoomPal22:           incbin   "assets_packed/graphics/roompalettes/pal022.pal"
RoomPal23:           incbin   "assets_packed/graphics/roompalettes/pal023.pal"
RoomPal24:           incbin   "assets_packed/graphics/roompalettes/pal024.pal"
RoomPal25:           incbin   "assets_packed/graphics/roompalettes/pal025.pal"
RoomPal26:           incbin   "assets_packed/graphics/roompalettes/pal026.pal"
RoomPal27:           incbin   "assets_packed/graphics/roompalettes/pal027.pal"
RoomPal28:           incbin   "assets_packed/graphics/roompalettes/pal028.pal"
RoomPal29:           incbin   "assets_packed/graphics/roompalettes/pal029.pal"
RoomPal30:           incbin   "assets_packed/graphics/roompalettes/pal030.pal"
RoomPal31:           incbin   "assets_packed/graphics/roompalettes/pal031.pal"
RoomPal32:           incbin   "assets_packed/graphics/roompalettes/pal032.pal"
RoomPal33:           incbin   "assets_packed/graphics/roompalettes/pal033.pal"
RoomPal34:           incbin   "assets_packed/graphics/roompalettes/pal034.pal"
RoomPal35:           incbin   "assets_packed/graphics/roompalettes/pal035.pal"
RoomPal36:           incbin   "assets_packed/graphics/roompalettes/pal036.pal"
RoomPal37:           incbin   "assets_packed/graphics/roompalettes/pal037.pal"
RoomPal38:           incbin   "assets_packed/graphics/roompalettes/pal038.pal"
RoomPal39:           incbin   "assets_packed/graphics/roompalettes/pal039.pal"
RoomPal40:           incbin   "assets_packed/graphics/roompalettes/pal040.pal"
RoomPal41:           incbin   "assets_packed/graphics/roompalettes/pal041.pal"
RoomPal42:           incbin   "assets_packed/graphics/roompalettes/pal042.pal"
RoomPal43:           incbin   "assets_packed/graphics/roompalettes/pal043.pal"
RoomPal44:           incbin   "assets_packed/graphics/roompalettes/pal044.pal"
RoomPal45:           incbin   "assets_packed/graphics/roompalettes/pal045.pal"
RoomPal46:           incbin   "assets_packed/graphics/roompalettes/pal046.pal"
RoomPal47:           incbin   "assets_packed/graphics/roompalettes/pal047.pal"
RoomPal48:           incbin   "assets_packed/graphics/roompalettes/pal048.pal"
RoomPal49:           incbin   "assets_packed/graphics/roompalettes/pal049.pal"
RoomPal50:           incbin   "assets_packed/graphics/roompalettes/pal050.pal"
RoomPal51:           incbin   "assets_packed/graphics/roompalettes/pal051.pal"
RoomPal52:           incbin   "assets_packed/graphics/roompalettes/pal052.pal"
RoomPal53:           incbin   "assets_packed/graphics/roompalettes/pal053.pal"
RoomPal54:           incbin   "assets_packed/graphics/roompalettes/pal054.pal"
